name: Test Self-Hosted Runner (Windows)

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello using Windows PowerShell 5.1
        shell: powershell
        run: |
          Write-Host "✅ Running with Windows PowerShell 5.1!"
          Write-Host "PSVersion: $($PSVersionTable.PSVersion)"
