name: Test Self-Hosted Runner (Windows)

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello from Windows runner
        shell: powershell
        run: |
          Write-Host "✅ Hello from your Windows self-hosted runner! Success!"
